name: my_final_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  intl: ^0.17.0
  image_picker: ^0.8.6
  provider: ^6.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_database: ^10.0.9
  firebase_storage: ^11.0.10
  get_it: ^7.2.0
  local_auth: ^2.1.3
  permission_handler: ^10.2.0
  share_plus: ^6.3.0
  flutter_native_splash: ^2.2.17
  lottie: ^2.2.0
  persian_datetime_picker: ^2.5.0
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  bloc_test: ^9.1.0
  firebase_auth_mocks: ^0.9.3
  syncfusion_flutter_charts: ^20.4.48
  pie_chart: ^5.3.2
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
   - assets/logos/
   - assets/
  fonts:
   - family:  CustomIcons
     fonts:
      - asset: assets/fonts/CustomIcons.ttf

flutter_intl:
  enabled: true
