name: journal
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0

  intl: ^0.17.0
  image_picker: ^0.8.6
  fluttertoast: ^8.1.2
  fast_immutable_collections: ^8.1.0
  modal_bottom_sheet: ^2.1.2
  shared_preferences: ^2.0.15
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  go_router: ^6.0.1
  rxdart: ^0.27.7
  flutter_slidable: ^2.0.0
  logger: ^1.1.0
  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_database: ^10.0.9
  firebase_storage: ^11.0.10
  local_auth: ^2.1.3
  share_plus: ^6.3.0
  flutter_native_splash: ^2.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  drift_dev: ^2.4.1
  envied_generator: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/flutter_logo.png
    - assets/images/flutter_logo_dark.png
